#! /bin/bash

if [ $# -lt 3 ]
then
  echo "Usage: $0 inputfile outfile bpm"
  exit
fi

docker run --rm -it -v `pwd`:/mp3 lame --decode $1 $1.tmp.wav && \
docker run --rm -it -v `pwd`:/dir soundtouch $1.tmp.wav $1.$3.wav -bpm=$3 && \
docker run --rm -it -v `pwd`:/mp3 lame $1.$3.wav $2 && \
rm $1.tmp.wav $1.$3.wav
